#!/usr/bin/env python3
"""Build seed.sql from the CSVs in this directory. Idempotent upserts.

Run:  python3 supabase/seed/build.py > supabase/seed/seed.sql
Then apply seed.sql to the database (Supabase SQL editor or MCP execute_sql).
"""
import csv, datetime as dt, json, pathlib

here = pathlib.Path(__file__).parent

def q(s):
    return "'" + s.replace("'", "''") + "'"

out = ["-- Generated by supabase/seed/build.py. Do not edit by hand.", "begin;", ""]

out.append("insert into public.conferences (id, name, short_name, tier, sort_order) values")
rows = list(csv.DictReader(open(here / "conferences.csv")))
out.append(",\n".join(f"  ({q(r['id'])}, {q(r['name'])}, {q(r['short_name'])}, {q(r['tier'])}, {r['sort_order']})" for r in rows))
out.append("on conflict (id) do update set name = excluded.name, short_name = excluded.short_name, tier = excluded.tier, sort_order = excluded.sort_order;\n")

out.append("insert into public.schools (id, name, full_name, nickname, conference_id, city, state, generic_name, generic_nickname) values")
rows = list(csv.DictReader(open(here / "schools.csv")))
out.append(",\n".join(f"  ({q(r['id'])}, {q(r['name'])}, {q(r['full_name'])}, {q(r['nickname'])}, {q(r['conference_id'])}, {q(r['city'])}, {q(r['state'])}, {q(r['generic_name'])}, {q(r['generic_nickname'])})" for r in rows))
out.append("on conflict (id) do update set name = excluded.name, full_name = excluded.full_name, nickname = excluded.nickname, conference_id = excluded.conference_id, city = excluded.city, state = excluded.state, generic_name = excluded.generic_name, generic_nickname = excluded.generic_nickname;\n")
school_ids = {r["id"] for r in rows}

out.append("delete from public.rivalry_pairings;")
out.append("insert into public.rivalry_pairings (school_id, rival_school_id, rank) values")
rows = list(csv.DictReader(open(here / "rivalries.csv")))
for r in rows:
    assert r["school_id"] in school_ids, r
    assert r["rival_school_id"] in school_ids, r
out.append(",\n".join(f"  ({q(r['school_id'])}, {q(r['rival_school_id'])}, {r['rank']})" for r in rows) + ";\n")

# Seasons. Week 0 is the last Saturday of August; inputs lock at 16:00 UTC on
# the Saturday. Weeks 0-3 non-conference, 4-12 conference, 13 Rivalry Week,
# 14 championship. Status is set only when a season row is first created:
# re-running the seed never moves a season backward (season-rollover.md).
SEASONS = [(2026, dt.date(2026, 8, 29), "active"), (2027, dt.date(2027, 8, 28), "upcoming")]
for year, season_start, status in SEASONS:
    weeks = []
    for n in range(15):
        day = season_start + dt.timedelta(weeks=n)
        kind = "nonconference" if n <= 3 else "conference" if n <= 12 else "rivalry" if n == 13 else "championship"
        weeks.append((n, day, kind))
    ends = weeks[-1][1]
    out.append(f"insert into public.seasons (id, year, starts_on, ends_on, status) values ('{year}', {year}, '{season_start.isoformat()}', '{ends.isoformat()}', '{status}')")
    out.append("on conflict (id) do update set starts_on = excluded.starts_on, ends_on = excluded.ends_on;\n")
    out.append("insert into public.season_weeks (season_id, week_number, starts_on, locks_at, kind) values")
    out.append(",\n".join(f"  ('{year}', {n}, '{d.isoformat()}', '{d.isoformat()}T16:00:00Z', {q(k)})" for n, d, k in weeks))
    out.append("on conflict (season_id, week_number) do update set starts_on = excluded.starts_on, locks_at = excluded.locks_at, kind = excluded.kind;\n")

config = [
    ("FACTION_CAP", 100, "Active members per faction. docs/phase-0/sharding-and-rivalry.md §4"),
    ("DORMANCY_DAYS", 30, "Days without login before a seat drops to alumni"),
    ("OFFICER_COUNT", 5, "Officers per faction, excluding the leader"),
    ("LEAGUE_OPEN_SEASONS", 1, "Seasons a League accepts placement before it is settled"),
    ("FACTION_SCORING_N", 50, "Faction weekly score is the sum of its top N program results"),
    ("TRANSFER_WINDOW", "offseason", "When a program may transfer Leagues"),
    ("SECONDARY_RIVALRIES_MAX", 2, "Rivalry pairings per school beyond the primary"),
    ("STARTING_CASH", 500, "Budget a new program starts with"),
    ("COLLECT_CAP_HOURS", 8, "Booster income stops accruing after this many hours uncollected"),
    ("MAX_CONCURRENT_UPGRADES", 1, "Facility upgrades a program can run at once"),
    ("SCOUT_COOLDOWN_HOURS", 4, "Hours between scouting trips"),
    ("SCOUT_SHARDS", 5, "Shards granted per scouting trip"),
    ("STAFF_LEVEL_COST_BASE", 200, "Cash to level a coach: base times current level"),
    ("CHALLENGE_LOCK_MINUTES", 10, "Minutes after a challenge is issued before it locks and resolves"),
    ("POINTS_PER_EDGE", 28, "Expected points per unit of facet edge. docs/phase-3/power-and-matchups.md §8"),
    ("BASE_POINTS", 24, "Expected points for an even matchup"),
    ("SCORE_NOISE_SD_TENTHS", 85, "Standard deviation of score noise, in tenths of a point"),
    ("HOUSE_MIN_POWER", 50, "Floor for a house program's power; above it, the house matches the League's human average"),
    ("WIN_POINTS", 3, "Standings points a program earns for a League win"),
    ("LOSS_POINTS", 1, "Standings points a program earns for a League loss"),
]
out.append("insert into public.facilities (id, name, description, sort_order) values")
rows = list(csv.DictReader(open(here / "facilities.csv")))
out.append(",\n".join(f"  ({q(r['id'])}, {q(r['name'])}, {q(r['description'])}, {r['sort_order']})" for r in rows))
out.append("on conflict (id) do update set name = excluded.name, description = excluded.description, sort_order = excluded.sort_order;\n")

out.append("insert into public.facility_levels (facility_id, level, cost, duration_seconds, income_per_hour, power) values")
rows = list(csv.DictReader(open(here / "facility_levels.csv")))
out.append(",\n".join(f"  ({q(r['facility_id'])}, {r['level']}, {r['cost']}, {r['duration_seconds']}, {r['income_per_hour'] or 'null'}, {r['power']})" for r in rows))
out.append("on conflict (facility_id, level) do update set cost = excluded.cost, duration_seconds = excluded.duration_seconds, income_per_hour = excluded.income_per_hour, power = excluded.power;\n")

out.append("insert into public.facility_facets (facility_id, rushing, passing, run_defense, pass_defense) values")
rows = list(csv.DictReader(open(here / "facility_facets.csv")))
out.append(",\n".join(f"  ({q(r['facility_id'])}, {r['rushing']}, {r['passing']}, {r['run_defense']}, {r['pass_defense']})" for r in rows))
out.append("on conflict (facility_id) do update set rushing = excluded.rushing, passing = excluded.passing, run_defense = excluded.run_defense, pass_defense = excluded.pass_defense;\n")

out.append("insert into public.emphases (id, name, blurb, sort_order, rushing, passing, run_defense, pass_defense) values")
rows = list(csv.DictReader(open(here / "emphases.csv")))
out.append(",\n".join(f"  ({q(r['id'])}, {q(r['name'])}, {q(r['blurb'])}, {r['sort_order']}, {r['rushing']}, {r['passing']}, {r['run_defense']}, {r['pass_defense']})" for r in rows))
out.append("on conflict (id) do update set name = excluded.name, blurb = excluded.blurb, sort_order = excluded.sort_order, rushing = excluded.rushing, passing = excluded.passing, run_defense = excluded.run_defense, pass_defense = excluded.pass_defense;\n")

out.append("insert into public.staff (id, name, role, rarity, base_power, power_per_level, unlock_shards, star_shards, rushing, passing, run_defense, pass_defense, sort_order) values")
rows = list(csv.DictReader(open(here / "staff.csv")))
out.append(",\n".join(f"  ({q(r['id'])}, {q(r['name'])}, {q(r['role'])}, {q(r['rarity'])}, {r['base_power']}, {r['power_per_level']}, {r['unlock_shards']}, {r['star_shards']}, {r['rushing']}, {r['passing']}, {r['run_defense']}, {r['pass_defense']}, {r['sort_order']})" for r in rows))
out.append("on conflict (id) do update set name = excluded.name, role = excluded.role, rarity = excluded.rarity, base_power = excluded.base_power, power_per_level = excluded.power_per_level, unlock_shards = excluded.unlock_shards, star_shards = excluded.star_shards, rushing = excluded.rushing, passing = excluded.passing, run_defense = excluded.run_defense, pass_defense = excluded.pass_defense, sort_order = excluded.sort_order;\n")

out.append("insert into public.daily_task_types (id, label, detector, reward_cash, sort_order) values")
rows = list(csv.DictReader(open(here / "daily_task_types.csv")))
out.append(",\n".join(f"  ({q(r['id'])}, {q(r['label'])}, {q(r['detector'])}, {r['reward_cash']}, {r['sort_order']})" for r in rows))
out.append("on conflict (id) do update set label = excluded.label, detector = excluded.detector, reward_cash = excluded.reward_cash, sort_order = excluded.sort_order;\n")

out.append("insert into public.faction_goal_types (id, label, blurb, metric, per_member, min_target, reward_cash, sort_order) values")
rows = list(csv.DictReader(open(here / "faction_goal_types.csv")))
out.append(",\n".join(f"  ({q(r['id'])}, {q(r['label'])}, {q(r['blurb'])}, {q(r['metric'])}, {r['per_member']}, {r['min_target']}, {r['reward_cash']}, {r['sort_order']})" for r in rows))
out.append("on conflict (id) do update set label = excluded.label, blurb = excluded.blurb, metric = excluded.metric, per_member = excluded.per_member, min_target = excluded.min_target, reward_cash = excluded.reward_cash, sort_order = excluded.sort_order;\n")

out.append("insert into public.mission_types (id, label, detector, target, reward_cash, sort_order) values")
rows = list(csv.DictReader(open(here / "mission_types.csv")))
out.append(",\n".join(f"  ({q(r['id'])}, {q(r['label'])}, {q(r['detector'])}, {q(r['target'])}, {r['reward_cash']}, {r['sort_order']})" for r in rows))
out.append("on conflict (id) do update set label = excluded.label, detector = excluded.detector, target = excluded.target, reward_cash = excluded.reward_cash, sort_order = excluded.sort_order;\n")

out.append("insert into public.game_config (key, value, description) values")
out.append(",\n".join(f"  ({q(k)}, {q(json.dumps(v))}::jsonb, {q(d)})" for k, v, d in config))
out.append("on conflict (key) do update set value = excluded.value, description = excluded.description, updated_at = now();\n")

out.append("commit;")
print("\n".join(out))
